-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 12:36:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sea_Cruise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sea_Cruise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sea_Cruise` DEFAULT CHARACTER SET utf8 ;
USE `Sea_Cruise` ;

-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Client` (
  `idClient` INT NOT NULL,
  `nom_cl` VARCHAR(20) NULL,
  `prenom_cl` VARCHAR(20) NULL,
  `@mail_cl` VARCHAR(50) NULL,
  `tel_cl` INT NOT NULL,
  `mdp` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `Date_naissance` DATE NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Admin` (
  `idAdmin` INT NOT NULL,
  `nom_admin` VARCHAR(20) NULL,
  `prenom_admin` VARCHAR(20) NULL,
  `@mail_admin` VARCHAR(60) NULL,
  `num_tel_admin` INT NOT NULL,
  `mdp_admin` VARCHAR(45) NULL,
  `date_naiss_admin` DATE NULL,
  `ville_admin` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Bateau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Bateau` (
  `idBateau` INT NOT NULL,
  `libellé_bateau` VARCHAR(45) NULL,
  `description_bateau` LONGTEXT NULL,
  `nombre_chambres` INT NULL,
  `nbre_place` INT NULL,
  PRIMARY KEY (`idBateau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Ville` (
  `idVille` INT NOT NULL,
  `nom_ville` VARCHAR(45) NULL,
  `description_ville` LONGTEXT NULL,
  `port` VARCHAR(45) NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Reservation` (
  `idReservation` INT NOT NULL,
  `date_reservation` DATE NULL,
  `montant` INT NOT NULL,
  `Bateau_idBateau` INT NOT NULL,
  `Ville_idVille` INT NOT NULL,
  `nbre_places` INT NULL,
  PRIMARY KEY (`idReservation`, `Bateau_idBateau`, `Ville_idVille`),
  INDEX `fk_Reservation_Bateau1_idx` (`Bateau_idBateau` ASC) VISIBLE,
  INDEX `fk_Reservation_Ville1_idx` (`Ville_idVille` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Bateau1`
    FOREIGN KEY (`Bateau_idBateau`)
    REFERENCES `Sea_Cruise`.`Bateau` (`idBateau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Ville1`
    FOREIGN KEY (`Ville_idVille`)
    REFERENCES `Sea_Cruise`.`Ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Croisière`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Croisière` (
  `idCroisière` INT NOT NULL,
  `libellé` VARCHAR(45) NULL,
  `trajet` VARCHAR(45) NULL,
  `date_depart` DATE NULL,
  `durée` VARCHAR(10) NULL,
  `description` LONGTEXT NULL,
  `Reservation_idReservation` INT NOT NULL,
  `Reservation_Bateau_idBateau` INT NOT NULL,
  `Reservation_Ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idCroisière`, `Reservation_idReservation`, `Reservation_Bateau_idBateau`, `Reservation_Ville_idVille`),
  INDEX `fk_Croisière_Reservation1_idx` (`Reservation_idReservation` ASC, `Reservation_Bateau_idBateau` ASC, `Reservation_Ville_idVille` ASC) VISIBLE,
  CONSTRAINT `fk_Croisière_Reservation1`
    FOREIGN KEY (`Reservation_idReservation` , `Reservation_Bateau_idBateau` , `Reservation_Ville_idVille`)
    REFERENCES `Sea_Cruise`.`Reservation` (`idReservation` , `Bateau_idBateau` , `Ville_idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Offre` (
  `idoffre` INT NOT NULL,
  `libellé_offre` VARCHAR(45) NULL,
  `description_offre` LONGTEXT NULL,
  PRIMARY KEY (`idoffre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Croisière_Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Croisière_Admin` (
  `Croisière_idCroisière` INT NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`Croisière_idCroisière`, `Admin_idAdmin`),
  INDEX `fk_Croisière_has_Admin_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Croisière_has_Admin_Croisière_idx` (`Croisière_idCroisière` ASC) VISIBLE,
  CONSTRAINT `fk_Croisière_has_Admin_Croisière`
    FOREIGN KEY (`Croisière_idCroisière`)
    REFERENCES `Sea_Cruise`.`Croisière` (`idCroisière`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Croisière_has_Admin_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `Sea_Cruise`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Offre_Croisière`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Offre_Croisière` (
  `Offre_idoffre` INT NOT NULL,
  `Croisière_idCroisière` INT NOT NULL,
  PRIMARY KEY (`Offre_idoffre`, `Croisière_idCroisière`),
  INDEX `fk_Offre_has_Croisière_Croisière1_idx` (`Croisière_idCroisière` ASC) VISIBLE,
  INDEX `fk_Offre_has_Croisière_Offre1_idx` (`Offre_idoffre` ASC) VISIBLE,
  CONSTRAINT `fk_Offre_has_Croisière_Offre1`
    FOREIGN KEY (`Offre_idoffre`)
    REFERENCES `Sea_Cruise`.`Offre` (`idoffre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_has_Croisière_Croisière1`
    FOREIGN KEY (`Croisière_idCroisière`)
    REFERENCES `Sea_Cruise`.`Croisière` (`idCroisière`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sea_Cruise`.`Client_Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sea_Cruise`.`Client_Reservation` (
  `Client_idClient` INT NOT NULL,
  `Reservation_idReservation` INT NOT NULL,
  `Reservation_Bateau_idBateau` INT NOT NULL,
  `Reservation_Ville_idVille` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Reservation_idReservation`, `Reservation_Bateau_idBateau`, `Reservation_Ville_idVille`),
  INDEX `fk_Client_has_Reservation_Reservation1_idx` (`Reservation_idReservation` ASC, `Reservation_Bateau_idBateau` ASC, `Reservation_Ville_idVille` ASC) VISIBLE,
  INDEX `fk_Client_has_Reservation_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Reservation_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `Sea_Cruise`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Reservation_Reservation1`
    FOREIGN KEY (`Reservation_idReservation` , `Reservation_Bateau_idBateau` , `Reservation_Ville_idVille`)
    REFERENCES `Sea_Cruise`.`Reservation` (`idReservation` , `Bateau_idBateau` , `Ville_idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
